version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: cat-labo-ligess_ligess_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  ligess:
    image: ghcr.io/cat-labo/ligess:master
    user: "1000:1000"
    restart: on-failure
    environment:
      HOST: "0.0.0.0"
      PORT: "3000"
      LIGESS_LN_BACKEND: "LND"
      LIGESS_LND_LEST: "https://${APP_LIGHTNING_NODE_IP}:${APP_LIGHTNING_NODE_REST_PORT}"
      LIGESS_LND_MACAROON: "${APP_LIGHTNING_MACAROON_INVOICES}"
